jobs:
- job: Node_ServiceBus_Function_Build_and_Deploy
  pool:
    name: Hosted Ubuntu 1604
    demands: 
    - npm
    - node.js
  steps:
  - task: DeleteFiles@1
    displayName: 'Delete files from functions/serviceBusFunction/'
    inputs:
      SourceFolder: functions/serviceBusFunction/
      Contents: function.json

  - template: ./build.yaml
    parameters:
      ConnectedServiceName: $(ConnectedServiceName)
      RootFolder: 'functions'
