# a build with no CI
trigger: none

jobs:
- job: Node_EventGrid_HTTP_Function_Build_and_Deploy
  pool:
    name: Hosted Ubuntu 1604
    demands: 
    - npm
    - node.js

  variables:
    ConnectedServiceName_local: $(ConnectedServiceName)
    namePrefix_local: $(namePrefix)

  steps:
  - bash: |
     rm -rf mydir serviceBusFunction
     mv eventGridFunction PurchaseItinerary
    workingDirectory: functions
    displayName: 'Rename folder to PurchaseItinerary'

  - template: ./build-appservice.yaml
    parameters:
      ConnectedServiceName: $(ConnectedServiceName)
      RootFolder: 'functions'

  - task: AzureCLI@1
    displayName: 'Azure CLI - Running configuration.ps1 and Deploy'
    inputs:
      azureSubscription: '${{ variables.ConnectedServiceName_local }}'
      scriptPath: configEventGrid.bash
      arguments: $(namePrefix_local)
      workingDirectory: $(Build.sourcesDirectory)      
    condition: and(always(), eq(variables['eventing'], 'eventgrid'))