# a build with no CI
trigger: none

jobs:
- job: Node_ServiceBus_Function_Build_and_Deploy
  pool:
    name: Hosted Ubuntu 1604
    demands: 
    - npm
    - node.js
  steps:
  - task: DeleteFiles@1
    displayName: 'Delete files from functions/serviceBusFunction/'
    inputs:
      SourceFolder: functions/serviceBusFunction/
      Contents: function.json

  - template: ./build-appservice.yaml
    parameters:
      ConnectedServiceName: $(ConnectedServiceName)
      RootFolder: 'functions'

  - task: AzureCLI@1
    displayName: 'Azure CLI - Running configuration.ps1 and Deploy'
    inputs:
      azureSubscription: '${{ variables.ConnectedServiceName_local }}'
      scriptLocation: inlineScript
      inlineScript: |
        sub=(az account show --query id --output tsv)
        url=(az keyvault secret show --vault-name "kv${{ variables.namePrefix_local }}" --name "ContosoTravel--ServiceFQDN" --query value --output tsv)
        topicId=(az eventgrid topic list --resource-group rg-{{ variables.namePrefix_local }} --subscription $sub --query [].id --output tsv)
        az eventgrid event-subscription create --name {{ variables.namePrefix_local }}PurchaseItinerarySub --source-resource-id $topicId --endpoint $url
      workingDirectory: $(Build.sourcesDirectory)      
    condition: and(always(), eq(variables['eventing'], 'eventgrid'))