# a build with no CI
trigger: none

jobs:
- job: Node_ServiceBus_Function_Build_and_Deploy
  pool:
    name: Hosted Ubuntu 1604
    demands: 
    - npm
    - node.js
  steps:
  - task: DeleteFiles@1
    displayName: 'Delete files from functions/eventGridFunction/'
    inputs:
      SourceFolder: functions/eventGridFunction/
      Contents: function.json

  - template: ./build-appservice.yaml
    parameters:
      ConnectedServiceName: $(ConnectedServiceName)
      RootFolder: 'functions'

