# a build with no CI
trigger: none

jobs:
- job: Node_Web_Build_and_Deploy
  pool:
    name: Hosted Ubuntu 1604
    demands: 
    - npm
    - node.js
  steps:
  - template: ./build.yaml
    parameters:
      ConnectedServiceName: $(ConnectedServiceName)
      RootFolder: 'web'

